
name: Validate on MR
on:
  pull_request:
    branches:
      [ main ]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2.7.1
          with:
            flutter-version: '2.5.3'
            cache: true
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter build apk
        - name: Upload apk artifacts
          uses: actions/upload-artifact@v3
          with:
            name: apk-file
            retention-days: 2
            if-no-files-found: error
            path: |
              build/app/outputs/flutter-apk/app-release.apk